apiVersion: apps/v1
kind: Deployment
metadata:
  name: restro-app
  labels:
    app: restro-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: restro-app
  template:
    metadata:
      labels:
        app: restro-app
    spec:
      containers:
        - name: restro-app-cont
          image: dockeramod2chaurasia/restro-app:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/restro"
            - name: SPRING_DATASOURCE_USERNAME
              value: "amod"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "amod"
---
apiVersion: v1
kind: Service
metadata:
  name: restro-app-service
  labels:
    app: spring-boot-app
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000  # You can choose any available port in your cluster
  selector:
    app: restro-app